# Generated by Django 4.1.3 on 2022-11-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infoklasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='prodcheck',
            old_name='content',
            new_name='DetailInfo',
        ),
        migrations.RenameField(
            model_name='prodcheck',
            old_name='date_posted',
            new_name='EventDay',
        ),
        migrations.RenameField(
            model_name='prodcheck',
            old_name='title',
            new_name='Typ',
        ),
    ]
